name: ibm-ai-capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - dash==1.14.0
  - fbprophet=0.6
  - flask=1.1.2
  - ipykernel=5.3.4
  - jupyter=1.0.0
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - numpy=1.19.1
  - pandas=1.1.1
  - python=3.7.6
  - plotly=4.9.0
  - requests=2.24.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - unittest2=1.1.0